version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    networks:
      - todo-net
  app:
    image: getting-started
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todos
    networks:
      - todo-net
volumes:
  todo-mysql-data:
networks:
  todo-net: